server:
  port: 8888
encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
spring:
  security:
    user:
      name: rxpfarm
      password: password11122022
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rortegaj/configService
          search-paths:
            - station*
          repos:
            perf:
              pattern: '*/perf'
              uri: https://github.com/rortegaj/configService-perf2
              search-paths:
                - 'station*'